### ISSUE TITLE
Page shift (about us)

### ISSUE THREAD

**Issue by pboorm** [astro-soton/astroweb#8]
Love the look of the new website!  Just a minor thing - if you click on 'Work/Study here', 'Internal' or 'People & contact', the page is slightly shifted so that 'ABOUT US' appears underneath the main banner.

**Comment by jhmatthews** [comment]
Is this fixed now @pboorm ? A bit concerned by loading time of the javascript header at the moment too.

**Comment by chrisfrohmaier** [comment]
So the java i've put in isn't all to do with the header. There is a part of the java which holds the page until all the content has loaded. If you remove that part of the java, then yes, the page loads quicker but it doesn't have any of the css styling which suddenly pops in. This doesn't look good. The poor load times are because a lot of our content is poorly managed for size and so it takes a while for everything to load.
I don't know enough about web development to optimise this and it was the only solutions i could find. 

Feel free to change some of this to make it load faster, and remove the java.

**Comment by pboorm** [comment]
Yep, the problem's now fixed.  Thanks!
